### ISSUE TITLE
Planning v2.0 release

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/loquat#54]
Some essential things that have to be done:
- [ ] #52: Check that datamappings have all data keys defined
- [ ] #42: Check that all input data-keys have distinct labels
- [ ] #53: Stabilize/update dependencies before the release

The rest of the things are not essential for the v2.0 release, some of them are important but can be implemented in the [v2.1](https://github.com/ohnosequences/loquat/milestones/v2.1)

The plan is:

- [ ] 1. fix the issues under the [v2.0](https://github.com/ohnosequences/loquat/milestones/v2.0) milestone
- [ ] 2. release statika-2.0-RC1, and release loquat-2.0-RC1
- [ ] 3. test it with some real project, if there are some new issues/bugs, add them to the milestone
- [ ] 4. fix them, release RC2 with these fixes and updates of all dependencies (#53)
- [ ] 5. test again, if no major problems detected, release v2.0

**Comment by laughedelic** [comment]
Released [2.0.0-M7](https://github.com/ohnosequences/loquat/releases/tag/v2.0.0-M7) with #52
